# Generated by Django 5.0.4 on 2024-05-27 00:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('username', models.CharField(blank=True, max_length=30)),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('dni', models.CharField(blank=True, max_length=10)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('birthdate', models.DateField(blank=True, default='1990-01-01')),
                ('hide_email', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=200)),
                ('fecha', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad', models.CharField(max_length=50)),
                ('dirección', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(max_length=1000, validators=[django.core.validators.MinLengthValidator(10, 'Este campo debe contener al menos 10 caracteres')])),
                ('categoria', models.IntegerField(choices=[(1, '$0-$4999'), (2, '$5000-$9999'), (3, '$10000+')])),
                ('fecha_de_publicacion', models.DateTimeField(auto_now=True)),
                ('imagen', models.ImageField(blank=True, upload_to='media/')),
                ('promocionado', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to=settings.AUTH_USER_MODEL)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='tt_app.sucursal')),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=200)),
                ('fecha', models.DateField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tt_app.producto')),
                ('respuesta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tt_app.respuesta')),
            ],
        ),
        migrations.CreateModel(
            name='Trueque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField()),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('rango_horario', models.IntegerField(choices=[(1, 'Turno Mañana: 8 AM'), (2, 'Turno Mañana: 9 AM'), (3, 'Turno Mañana: 10 AM'), (4, 'Turno Mañana: 11 AM'), (5, 'Turno Tarde: 3 PM'), (6, 'Turno Tarde: 4 PM'), (7, 'Turno Tarde: 5 PM'), (8, 'Turno Tarde: 6 PM'), (9, 'Turno Tarde: 7 PM')])),
                ('estado', models.IntegerField(choices=[(1, 'Solicitado'), (2, 'Aceptado'), (3, 'Rechazado'), (4, 'Cancelado por solicitante'), (5, 'Cancelado por empleado'), (6, 'Concretado')])),
                ('producto_solicitado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trueques', to='tt_app.producto')),
                ('producto_solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trueque', to='tt_app.producto')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trueques', to='tt_app.sucursal')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_unidades', models.IntegerField()),
                ('precio_unitario', models.FloatField()),
                ('nombre_producto', models.CharField(max_length=200)),
                ('trueque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tt_app.trueque')),
            ],
        ),
    ]
