# Generated by Django 5.0.6 on 2024-05-29 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tt_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trueque',
            name='producto_solicitado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trueque_solicitado', to='tt_app.producto'),
        ),
    ]
