# Generated by Django 5.0.6 on 2024-05-28 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tt_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sucursal',
            old_name='dirección',
            new_name='direccion',
        ),
    ]
