# Generated by Django 5.0.6 on 2024-05-29 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tt_app', '0002_alter_trueque_producto_solicitado'),
        ('tt_app', '0002_rename_dirección_sucursal_direccion'),
    ]

    operations = [
    ]
