# Generated by Django 5.0.6 on 2024-06-13 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tt_app', '0003_venta_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
