# Generated by Django 5.0.6 on 2024-05-30 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tt_app', '0003_merge_20240529_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='reservado',
            field=models.BooleanField(default=False),
        ),
    ]
