# Generated by Django 5.0.6 on 2024-05-30 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tt_app', '0004_producto_reservado'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='disponible',
            field=models.BooleanField(default=False),
        ),
    ]
