# Generated by Django 5.0.4 on 2024-05-29 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tt_app', '0004_alter_pregunta_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='fecha',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
