# Generated by Django 5.0.6 on 2024-06-13 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tt_app', '0004_venta_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='respuesta',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
