# Generated by Django 5.0.6 on 2024-06-13 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tt_app', '0004_usuario_sucursal'),
        ('tt_app', '0005_pregunta_activo_respuesta_activo'),
    ]

    operations = [
    ]
