# Generated by Django 5.0.6 on 2024-06-23 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tt_app', '0006_merge_20240613_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='fecha_hasta_promocion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fecha_de_publicacion',
            field=models.DateTimeField(),
        ),
    ]
