# Generated by Django 5.0.6 on 2024-05-31 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tt_app', '0005_alter_pregunta_fecha'),
        ('tt_app', '0006_sucursal_activo'),
    ]

    operations = [
    ]
