# Generated by Django 5.0.6 on 2024-06-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tt_app', '0007_merge_0005_alter_pregunta_fecha_0006_sucursal_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trueque',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Solicitado'), (2, 'Aceptado'), (3, 'Rechazado'), (4, 'Cancelado por solicitante'), (5, 'Cancelado por empleado'), (6, 'Concretado'), (7, 'Pendiente'), (8, 'Cancelado por solicitado'), (10, 'Concreto otro  trueque')]),
        ),
    ]
