# Generated by Django 5.0.6 on 2024-06-04 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tt_app', '0008_alter_trueque_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='trueque',
            name='motivo_rechazo',
            field=models.IntegerField(choices=[(1, 'Producto ya no disponible'), (2, 'Falta de interes en el producto ofrecido'), (3, 'Falta de disponibilidad en horaria'), (4, 'Falta de disponibilidad en la fecha solicitada'), (5, 'Otros motivos')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='trueque',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Solicitado'), (2, 'Aceptado'), (3, 'Rechazado'), (4, 'Pendiente'), (5, 'Concretado'), (6, 'Cancelado por empleado'), (7, 'Cancelado por solicitante'), (8, 'Cancelado por solicitado'), (9, 'concretó otro trueque')]),
        ),
    ]
