# Generated by Django 5.0.6 on 2024-06-04 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tt_app', '0008_alter_trueque_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='trueque',
            name='opcion_rechazo',
            field=models.IntegerField(choices=[(1, 'Producto ya no disponible'), (2, 'Falta de interés en el producto ofrecido'), (3, 'Falta de disponibilidad horaria'), (4, 'Falta de disponibilidad en la fecha solicitada'), (5, 'Otros motivos')], null=True),
        ),
    ]
