# Generated by Django 5.0.6 on 2024-06-04 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tt_app', '0010_alter_trueque_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trueque',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='trueque',
            name='rango_horario',
            field=models.IntegerField(choices=[(1, 'Turno Mañana: 8 AM'), (2, 'Turno Mañana: 9 AM'), (3, 'Turno Mañana: 10 AM'), (4, 'Turno Mañana: 11 AM'), (5, 'Turno Tarde: 3 PM'), (6, 'Turno Tarde: 4 PM'), (7, 'Turno Tarde: 5 PM'), (8, 'Turno Tarde: 6 PM'), (9, 'Turno Tarde: 7 PM')], default=1),
        ),
    ]
