# Generated by Django 5.0.6 on 2024-06-05 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tt_app', '0012_rename_rango_horario_trueque_horario_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trueque',
            old_name='fecha',
            new_name='fecha_de_solicitud',
        ),
    ]
