# Generated by Django 5.0.6 on 2024-06-05 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tt_app', '0014_alter_trueque_fecha_de_solicitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='trueque',
            name='fecha_programada',
            field=models.DateField(blank=True, default='2025-01-01'),
        ),
    ]
