# Generated by Django 5.0.6 on 2024-06-05 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tt_app', '0015_trueque_fecha_programada'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trueque',
            old_name='fecha_de_solicitud',
            new_name='fecha',
        ),
    ]
