# Generated by Django 5.0.6 on 2024-06-05 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tt_app', '0009_trueque_opcion_rechazo'),
        ('tt_app', '0016_rename_fecha_de_solicitud_trueque_fecha'),
    ]

    operations = [
    ]
