# Generated by Django 5.0.4 on 2024-05-05 12:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='NULL', max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=25)),
                ('DNI', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(validators=[django.core.validators.MinLengthValidator(10, 'Este campo debe contener al menos 10 caracteres')])),
                ('categoria', models.IntegerField(choices=[(1, '$0-$4999'), (2, '$5000-$9999'), (3, '$10000+')])),
                ('fecha_de_publicacion', models.DateTimeField(auto_now=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('promocionado', models.BooleanField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='tl_app.usuario')),
            ],
        ),
    ]
