# Generated by Django 5.0.4 on 2024-05-05 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tl_app', '0002_usuario_fecha_de_nacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='promocionado',
            field=models.BooleanField(default=False),
        ),
    ]
